openapi: 3.0.3
info:
  title: HORIZON GUARD - ARMY CH

  version: 1.0.0

servers:
  - url: localhost:3001
tags:
  - name: sensor

paths:
  /root:
    get:
      tags:
        - root
      summary: Check availability of service

      responses:
        '200':
          description: Successful
        '400':
          description: Wrong input given
        '500':
          description: Server error

  /horizon-guard/register:
    post:
      tags:
        - sensor
      summary: Register a new sensor onto the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [thermal, radar, vibration]
                  example: 'thermal'
      responses:
        '200':
          description: Successfully processed the request and returned the sensorId.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sensorId:
                    type: string
                    example: '1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed'
                    description: Sensor id as uuidv4
        '400':
          description: Wrong input given

        '500':
          description: Server error

  /horizon-guard/transferdata:
    post:
      tags:
        - sensor
      summary: Send data update from sensor to core
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sensorId:
                  type: string
                  example: '1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed'
                  description: Sensor id as uuidv4
                dataThermal:
                  type: string
                  example: 'RGlyIGlzY2ggbGFuZ3dpbGxpZyB3ZW5uIGRhcyBpbmUgcG9zdGV0IGhlc2NoIHVuZCBkZWNvZGVkIGhlc2No'
                  format: base64
                dataRadar:
                  type: string
                  example: 'RGlyIGlzY2ggbGFuZ3dpbGxpZyB3ZW5uIGRhcyBpbmUgcG9zdGV0IGhlc2NoIHVuZCBkZWNvZGVkIGhlc2No'
                  format: base64
                dataVibration:
                  type: string
                  example: 'RGlyIGlzY2ggbGFuZ3dpbGxpZyB3ZW5uIGRhcyBpbmUgcG9zdGV0IGhlc2NoIHVuZCBkZWNvZGVkIGhlc2No'
                  format: base64

      responses:
        '200':
          description: Successfully saved the data
        '400':
          description: Wrong input given
        '401':
          description: Your sensor id is not registered. Please request a new one
        '500':
          description: Server error
